#!/usr/bin/env python3
"""
Regenerate the LightVoice launcher icon.

The mark is a level meter: five vertical bars with round caps, tallest in the middle.
It reads as "listening" at 48px, which a microphone silhouette does not, and it is
the same white-line-art-on-black language as the sibling Light Phone III tools.

Geometry is defined once in the 108x108 adaptive-icon canvas and emitted twice — as
Android vector paths and as raster fallbacks — so the two can never drift.

    python3 scripts/generate_icon.py

Needs Pillow. Rewrites app/src/main/res/{drawable,mipmap-*}.
"""

from __future__ import annotations

import os

from PIL import Image, ImageDraw

RES = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "res")

CANVAS = 108
SAFE = (18.0, 90.0)
STROKE = 5.0
CENTRE = 54.0
PITCH = 13.5
HALF_HEIGHTS = (10.0, 19.0, 29.0, 19.0, 10.0)

DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
SUPERSAMPLE = 8


def bars() -> list[tuple[float, float, float]]:
    """(x, y_top, y_bottom) centrelines, left to right."""
    first = CENTRE - PITCH * (len(HALF_HEIGHTS) - 1) / 2
    return [
        (first + i * PITCH, CENTRE - h, CENTRE + h)
        for i, h in enumerate(HALF_HEIGHTS)
    ]


def check_safe_zone() -> None:
    lo, hi = SAFE
    edge = STROKE / 2  # round caps extend half a stroke past the centreline
    for x, top, bottom in bars():
        for px, py in ((x - edge, top - edge), (x + edge, bottom + edge)):
            assert lo <= px <= hi and lo <= py <= hi, f"({px}, {py}) escapes the safe zone"


def write_vectors() -> None:
    paths = "\n".join(
        f'    <path\n'
        f'        android:strokeColor="#FFFFFF"\n'
        f'        android:strokeWidth="{STROKE}"\n'
        f'        android:strokeLineCap="round"\n'
        f'        android:pathData="M{x},{top} L{x},{bottom}" />'
        for x, top, bottom in bars()
    )
    foreground = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_icon.py — edit the script, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
{paths}
</vector>
"""
    background = """<?xml version="1.0" encoding="utf-8"?>
<!-- Pure black. On the Light Phone III's OLED these pixels are simply off. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#000000"
        android:pathData="M0,0h108v108h-108z" />
</vector>
"""
    drawable = os.path.join(RES, "drawable")
    os.makedirs(drawable, exist_ok=True)
    with open(os.path.join(drawable, "ic_launcher_foreground.xml"), "w") as f:
        f.write(foreground)
    with open(os.path.join(drawable, "ic_launcher_background.xml"), "w") as f:
        f.write(background)

    adaptive = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
"""
    anydpi = os.path.join(RES, "mipmap-anydpi-v26")
    os.makedirs(anydpi, exist_ok=True)
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        with open(os.path.join(anydpi, name), "w") as f:
            f.write(adaptive)


def render(px: int, circular: bool) -> Image.Image:
    """
    Rasterise at SUPERSAMPLE times the target and downsample, because Pillow has no
    antialiasing of its own and a 48px icon drawn straight looks chewed.
    """
    size = px * SUPERSAMPLE
    scale = size / CANVAS
    image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)

    if circular:
        draw.ellipse((0, 0, size - 1, size - 1), fill=(0, 0, 0, 255))
    else:
        draw.rectangle((0, 0, size - 1, size - 1), fill=(0, 0, 0, 255))

    width = STROKE * scale
    for x, top, bottom in bars():
        draw.line(
            (x * scale, top * scale, x * scale, bottom * scale),
            fill=(255, 255, 255, 255),
            width=int(round(width)),
        )
        # Round caps, which Pillow's line() does not draw.
        for y in (top, bottom):
            r = width / 2
            draw.ellipse(
                (x * scale - r, y * scale - r, x * scale + r, y * scale + r),
                fill=(255, 255, 255, 255),
            )

    return image.resize((px, px), Image.LANCZOS)


def write_rasters() -> None:
    for density, px in DENSITIES.items():
        folder = os.path.join(RES, f"mipmap-{density}")
        os.makedirs(folder, exist_ok=True)
        render(px, circular=False).save(os.path.join(folder, "ic_launcher.png"))
        render(px, circular=True).save(os.path.join(folder, "ic_launcher_round.png"))


if __name__ == "__main__":
    check_safe_zone()
    write_vectors()
    write_rasters()
    print("icon written")
